### ISSUE TITLE
Define what is needed for a project and add to contributing section in README

### ISSUE THREAD

**Issue by psophis** [RxSwiftCommunity/rxswiftcommunity.github.io#4]
Title, link, description, etc...

Authorization from project owner?

**Comment by ashfurrow** [comment]
Hmm, good question! Not sure if we need authorization. Thoughts?

**Comment by esttorhe** [comment]
I don't think authorization is required (but that's silly old me) but perhaps contacting them once a `PR` is made to include a project so they know about it and can request take down if desired?

**Comment by psophis** [comment]
[awesome-swift CONTRIBUTING](https://github.com/matteocrippa/awesome-swift/blob/master/CONTRIBUTING.md) doens't list any authorization. Not that they are correct. I'd assume that any public project is fair game for linking to. But the owner should have the right to modify anything related or ask the project to be removed, obviously.

**Comment by ashfurrow** [comment]
Sounds like we're OK with just a name, link, and description. Makes sense? If that's the case, we'll need them formatted in the following yaml syntax:

```yaml
- name: Project Name
  link: http://whatever
  description: A paragraph of text that we'll display.

- name: Project Name
  link: http://whatever
  description: A paragraph of text that we'll display.

... and so on
```
