### ISSUE TITLE
How to add rxswift chinese documentation project?

### ISSUE THREAD

**Issue by beeth0ven** [RxSwiftCommunity/rxswiftcommunity.github.io#54]
Hi @freak4pc  @fpillet , I'm coming here to add RxSwift Chinese Documentation but  don't known which categories to choose. Could you give me some advises?

Sorry to trouble you again.

**Comment by freak4pc** [comment]
@beeth0ven 
I think you should make a PR and add to the bottom

```
  - name: Documentation & Resources
    items:
      - name: Chinese Documentation (Unofficial)
        link: ...
        description: ...
```

Then we can move the discussion to your PR
